enable_memory_catalog = false

[wal]
file_size = '50MB'
purge_interval = '10m'
purge_threshold = '1GB'
read_batch_size = 128
sync_write = false

[storage]
type = 'File'
data_home = '/var/lib/greptimedb/'

[http]
enable = true
addr = '0.0.0.0:4000'

[grpc]
enable = true
bind_addr = '0.0.0.0:4001'

[mysql]
enable = true
addr = '0.0.0.0:4002'

[influxdb]
enable = true

[prom_store]
enable = true

[postgres]
enable = true
addr = '0.0.0.0:4003'

[jaeger]
enable = true

[logging]
dir = "/var/log/greptimedb/"
