name: Sync

on:
  schedule: [{cron: "0 2 * * *"}]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: fetch-latest-release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repo: GreptimeTeam/greptimedb
          prerelease: true
          releaseNameRegEx: "Release v[\\.\\d]+-nightly-\\d{8}"
          latest: 1
      - id: update-pkgbuild
        run: |
          tag=${{steps.fetch-latest-release.outputs.tag_name}} ./update.sh
      - uses: peter-evans/create-pull-request@v4
        if: ${{ steps.update-pkgbuild.outputs.dirty }}
        with:
          token: ${{ github.token }}
          commit-message: "Update to ${{steps.fetch-latest-release.outputs.tag_name}}"
          committer: GitHub Action <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{steps.fetch-latest-release.outputs.tag_name}}
          delete-branch: true
          title: "Update AUR ${{steps.fetch-latest-release.outputs.tag_name}}"
          body: |
            Update package to: ${{steps.fetch-latest-release.outputs.tag_name}}
